global:
  namespace: ""
  host: "elma365.ru"
  edition: "standard"
  solution: "onPremise"
  env: "production"
  skipSslVerify: false
  labels:
    event-producer: "true"
  annotations: {}
  kubeVersion: ""
  ingress:
    timeoutSeconds: 300
    indexIsnull:
      enabled: false
    onpremiseTls:
      enabled: false
    annotations: {}
    ingressClassName: ""
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  backoffLimit: 5
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  holdingEnabled: false
  autoscaling:
    enabled: false
    type: "hpa"
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  companies:
    - '*'
  openshift: false
  monitoring:
    enabled: true
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: true
    alerts:
      enabled: false
    metrics:
      interval: 30s
  cronStartingDeadlineSeconds: ""
  cronTtlSecondsAfterFinished: ""
  cronActiveDeadlineSeconds: ""
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  podSecurityContext: {}
  securityContext: {}
  startupProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  lifecycle: {}
  setupJobTtlSecondsAfterFinished:
images:
  setup: ci-cd9c5d0e
  gateway: ci-4af457f1
image:
  repository: {}
  pullSecret: {}
appconfig:
  store:
    url:
      production: https://store.elma365.ru
      staging: https://store.s-elma365.ru
      _default: https://store.elma365.ru
  wopi:
    productionEndpoints:
      production: true
      _default: false
  settings:
    saveTestCode: ''
  app:
    maxWorkersCount: 5
    itemsExchangeTimeout: 3
    exchangeTimeout: 60m
    itemsExchangeImportChunkSize: 100
  ldap:
    attemptsMaxCount: 24
    delayBetweenAttempts: 5s
    importTimeout: 30m
  permissions:
    disableBuildIndex: false
ingress:
  annotations: {}
  gzip:
    enabled: true
    compLevel: 5
    minLength: 1024
nameOverride: main
podSecurityContext: {}
securityContext: {}
podAnnotations: {}
kubeVersion: ""
resourcesJobs: {}
resources:
  requests:
    memory: "1024Mi"
    cpu: "500m"
  limits:
    memory: "4Gi"
    cpu: "2000m"
autoscaling: {}
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
lifecycle: {}
annotations:
  ci.elma365.com/commit: "89b78ea6"
  ci.elma365.com/checksum: "cd9c5d0e"
  ci.elma365.com/job_id: "3502638"
  ci.elma365.com/timestamp: "2025-07-31T13:52:07+04:00"
  ci.elma365.com/pipeline_id: "610855"
