global:
  namespace: ""
  host: "elma365.ru"
  edition: "standard"
  solution: "onPremise"
  env: "production"
  skipSslVerify: false
  labels: {}
  annotations: {}
  kubeVersion: ""
  ingress:
    onpremiseTls:
      enabled: false
    annotations: {}
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  backoffLimit: 5
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    type: "hpa"
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  podSecurityContext: {}
  securityContext: {}
  startupProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  lifecycle: {}
  companies:
    - '*'
images:
  service: ci-0e00f1cb
image:
  repository: {}
  pullSecret: {}
nameOverride: notigate
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
kubeVersion: ""
autoscaling: {}
resourcesJobs: {}
resources:
  requests:
    memory: "386Mi"
    cpu: "150m"
  limits:
    memory: "1536Mi"
    cpu: "500m"
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
lifecycle: {}
notigate:
  labels:
    app: notigate
ingress:
  annotations: {}
annotations:
  ci.elma365.com/commit: "c9a86178"
  ci.elma365.com/checksum: "0e00f1cb"
  ci.elma365.com/job_id: "3375321"
  ci.elma365.com/timestamp: "2025-06-27T06:14:30+00:00"
  ci.elma365.com/pipeline_id: "595895"
