global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  skipSslVerify: false
  labels: {}
  annotations: {}
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
  holdingEnabled: false
  monitoring:
    enabled: true
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: true
    alerts:
      enabled: false
    metrics:
      interval: 30s
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  readinessProbe:
    httpGet:
      path: /ready
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  podSecurityContext: {}
  securityContext: {}
  startupProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  lifecycle: {}
images:
  service: ci-42f31c16
image:
  repository: {}
  pullSecret: {}
appconfig:
  httpTimeout: 1m
autoscaling: {}
nameOverride: messengers
podSecurityContext: {}
securityContext: {}
podAnnotations: {}
resourcesJobs: {}
resources: {}
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
lifecycle: {}
annotations:
  ci.elma365.com/commit: "2816d61a"
  ci.elma365.com/checksum: "42f31c16"
  ci.elma365.com/job_id: "3407681"
  ci.elma365.com/timestamp: "2025-07-08T08:30:59+00:00"
  ci.elma365.com/pipeline_id: "600138"
