apiVersion: v2
appVersion: 2025.4.6
dependencies:
- condition: messenger-inbox.enabled
  name: messenger-inbox
  repository: file://charts/messenger-inbox
  version: 0.1.0
- condition: messenger-instagram.enabled
  name: messenger-instagram
  repository: file://charts/messenger-instagram
  version: 0.1.0
- condition: messenger-livechat.enabled
  name: messenger-livechat
  repository: file://charts/messenger-livechat
  version: 0.1.0
- condition: messenger-other.enabled
  name: messenger-other
  repository: file://charts/messenger-other
  version: 0.1.0
- condition: messenger-telegram.enabled
  name: messenger-telegram
  repository: file://charts/messenger-telegram
  version: 0.1.0
- condition: messenger-telegrambot.enabled
  name: messenger-telegrambot
  repository: file://charts/messenger-telegrambot
  version: 0.1.0
- condition: messenger-viberbot.enabled
  name: messenger-viberbot
  repository: file://charts/messenger-viberbot
  version: 0.1.0
- condition: messenger-vkontakte.enabled
  name: messenger-vkontakte
  repository: file://charts/messenger-vkontakte
  version: 0.1.0
- condition: messenger-vkteamsbot.enabled
  name: messenger-vkteamsbot
  repository: file://charts/messenger-vkteamsbot
  version: 0.1.0
- condition: messenger-whatsapp.enabled
  name: messenger-whatsapp
  repository: file://charts/messenger-whatsapp
  version: 0.1.0
description: Elma365 full application chart
name: elma365
type: application
version: 2025.4.6
