global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  skipSslVerify: false
  labels: {}
  annotations: {}
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: Recreate
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  startupProbe:
    httpGet:
      path: /healthz
      port: http
    failureThreshold: 180
    periodSeconds: 10
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  lifecycle: {}
images:
  service: ci-8ab94891
image:
  repository: {}
  pullSecret: {}
appconfig:
  httpTimeout: 1m
nameOverride: messenger-vkontakte
podSecurityContext: {}
securityContext: {}
podAnnotations: {}
resourcesJobs: {}
autoscaling: {}
resources: {}
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
lifecycle: {}
annotations:
  ci.elma365.com/commit: "db469ed6"
  ci.elma365.com/checksum: "8ab94891"
  ci.elma365.com/job_id: "3366120"
  ci.elma365.com/timestamp: "2025-06-16T14:11:35+04:00"
  ci.elma365.com/pipeline_id: "594834"
