{{- $releaseName := .Release.Name }}
{{- $name := include "indicators.name" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "indicators.name" . }}
  labels:
    {{- include "indicators.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.global.autoscaling.enabled }}
  replicas: {{ if or (kindIs "float64" .Values.replicaCount) (kindIs "int64" .Values.replicaCount) }}{{ .Values.replicaCount }}{{ else }}{{ .Values.global.replicaCount }}{{ end }}
  {{ end }}
  selector:
    matchLabels:
      {{- include "indicators.selectorLabels" . | nindent 6 }}
  strategy: {{- toYaml .Values.global.updateStrategy | nindent 4 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.global.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "indicators.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- range .Values.global.image.pullSecret }}
        - name: {{ . }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.image.repository }}/elma365/indicators/service:{{ .Values.images.service }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.global.grpc_port }}
            - name: http
              containerPort: {{ .Values.global.http_port }}
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NAMESPACE
              value: {{ .Release.Namespace | quote }}
          envFrom:
            - configMapRef:
                name: elma365-env-config
                optional: true
            - secretRef:
                name: elma365-db-connections
                optional: true
      {{- if .Values.global.helmLibrary }}
          {{- include "helm-library.deployment.probes" . | indent 10 }}
          {{- include "helm-library.deployment.resources" . | indent 10 }}
          {{- include "helm-library.deployment.volumeMounts" . | indent 10 }}
          {{- include "helm-library.deployment.lifecycle" . | indent 10 }}
        {{- include "helm-library.deployment.volumes" . | indent 6 }}
        {{- include "helm-library.deployment.terminationgraceperiod" . | indent 6 }}
        {{- include "helm-library.deployment.scheduling" . | indent 6 }}
      {{- end }}
