global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  labels: {}
  annotations: {}
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  podSecurityContext: {}
  securityContext: {}
  startupProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  lifecycle: {}
images:
  service: ci-289642e7
image:
  repository: {}
  pullSecret: {}
autoscaling: {}
fullnameOverride: scheduler
nameOverride: scheduler
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resourcesJobs: {}
resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "1024Mi"
    cpu: "2000m"
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
lifecycle: {}
annotations:
  ci.elma365.com/commit: "396da14e"
  ci.elma365.com/checksum: "289642e7"
  ci.elma365.com/job_id: "3365021"
  ci.elma365.com/timestamp: "2025-06-16T14:00:00+04:00"
  ci.elma365.com/pipeline_id: "594788"
