global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  skipSslVerify: false
  labels: {}
  annotations: {}
  kubeVersion: ""
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    type: "hpa"
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  resources: {}
  resourceLimits: false
  resourcesJobs: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  podSecurityContext: {}
  securityContext: {}
  startupProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  lifecycle: {}
images:
  service: ci-d9280ac2
image:
  repository: {}
  pullSecret: {}
nameOverride: picasso
podSecurityContext: {}
securityContext: {}
podAnnotations: {}
kubeVersion: ""
autoscaling: {}
resourcesJobs: {}
resources:
  requests:
    memory: "150Mi"
    cpu: "150m"
  limits:
    memory: "555Mi"
    cpu: "555m"
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
lifecycle: {}
annotations:
  ci.elma365.com/commit: "33bc3f55"
  ci.elma365.com/checksum: "d9280ac2"
  ci.elma365.com/job_id: "3239920"
  ci.elma365.com/timestamp: "2025-05-15T13:35:26+00:00"
  ci.elma365.com/pipeline_id: "578104"
