apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "chat.name" . }}
  labels:
    {{- include "chat.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.global.autoscaling.enabled }}
  replicas: {{ if or (kindIs "float64" .Values.replicaCount) (kindIs "int64" .Values.replicaCount) }}{{ .Values.replicaCount }}{{ else }}{{ .Values.global.replicaCount }}{{ end }}
  {{ end }}
  selector:
    matchLabels:
      {{- include "chat.selectorLabels" . | nindent 6 }}
  strategy: {{- toYaml .Values.global.updateStrategy | nindent 4 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.global.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "chat.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.global.helmLibrary }}
      securityContext:
        {{- include "helm-library.podSecurityContext" . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
        {{- if .Values.image.pullSecret }}
        {{- range .Values.image.pullSecret }}
        - name: {{ . }}
        {{- end }}
        {{- else }}
        {{- range .Values.global.image.pullSecret }}
        - name: {{ . }}
        {{- end }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository | default .Values.global.image.repository }}/elma365/chat/service:{{ .Values.images.service }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.global.grpc_port }}
            - name: http
              containerPort: {{ .Values.global.http_port }}
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: ELMA365_WATCH_COMPANY
              value: {{ .Values.watchCompany | quote }}
            {{- if .Values.global.loadedUserExpirationPeriod }}
            - name: ELMA365_LOADED_USER_EXPIRATION_PERIOD
              value: {{ .Values.global.loadedUserExpirationPeriod | quote }}
            {{- else }}
            - name: ELMA365_LOADED_USER_EXPIRATION_PERIOD
              value: {{ default "48h" .Values.loadedUserExpirationPeriod | quote }}
            {{- end }}
            - name: ELMA365_SUPPORT_HOST
              value: {{ .Values.appconfig.support.host | quote }}
            - name: ELMA365_SUPPORT_INTEGRATION_ID
              value: {{ .Values.appconfig.support.integrationId | quote }}
            - name: ELMA365_SUPPORT_SECRET_KEY
              value: {{ .Values.appconfig.support.secretKey | quote }}
          {{- if .Values.global.helmLibrary }}
            {{- include "helm-library.deployment.env" . | indent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: elma365-env-config
                optional: true
            - secretRef:
                name: elma365-db-connections
                optional: true
      {{- if .Values.global.helmLibrary }}
          securityContext:
            {{- include "helm-library.deployment.securityContext" . | nindent 12 }}
          {{- include "helm-library.deployment.probes" . | indent 10 }}
          {{- include "helm-library.deployment.resources" . | indent 10 }}
          {{- include "helm-library.deployment.volumeMounts" . | indent 10 }}
          {{- include "helm-library.deployment.lifecycle" . | indent 10 }}
        {{- include "helm-library.deployment.volumes" . | indent 6 }}
        {{- include "helm-library.deployment.terminationgraceperiod" . | indent 6 }}
        {{- include "helm-library.deployment.scheduling" . | indent 6 }}
      {{- end }}
