global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  skipSslVerify: false
  labels: {}
  annotations: {}
  kubeVersion: ""
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  backoffLimit: 5
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    type: "hpa"
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: false
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: false
    alerts:
      enabled: false
    metrics:
      interval: 30s
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  podSecurityContext: {}
  securityContext: {}
  startupProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  lifecycle: {}
images:
  service: ci-adcb68c6
  setup: develop
image:
  repository: {}
  pullSecret: {}
nameOverride: lowcodecd
podSecurityContext: {}
securityContext: {}
podAnnotations: {}
kubeVersion: ""
autoscaling: {}
resources: {}
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
lifecycle: {}
lowcodecd:
  labels:
    app: lowcodecd
appconfig:
  limitsEnabled: false
  bindingTrialLimit: 1
  bindingPaidLimit: 5
  profileTrialLimit: 1
  profilePaidLimit: 10
annotations:
  ci.elma365.com/commit: "722e4f59"
  ci.elma365.com/checksum: "adcb68c6"
  ci.elma365.com/job_id: "3366029"
  ci.elma365.com/timestamp: "2025-06-09T16:51:21+04:00"
  ci.elma365.com/pipeline_id: "594825"
