global:
  namespace: ""
  host: elma365.ru
  edition: "standard"
  solution: "onPremise"
  env: "production"
  skipSslVerify: false
  labels: {}
  annotations: {}
  http_port: 3000
  grpc_port: 5000
  http_metrics: 3100
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  backoffLimit: 5
  image:
    repository: dreg.elewise.com:5005
    pullPolicy: IfNotPresent
    pullSecret:
      - regsecret
      - yandexsecret
      - customsecret
  autoscaling:
    enabled: false
    type: "hpa"
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  holdingEnabled: false
  monitoring:
    enabled: true
    namespace: ""
    provisioner: "k8s"
    dashboard:
      enabled: true
    alerts:
      enabled: false
    metrics:
      interval: 60s
  resourceLimits: false
  resourcesJobs: {}
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 1
    successThreshold: 1
  podSecurityContext: {}
  securityContext: {}
  startupProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  lifecycle: {}
images:
  service: ci-33ee6563
  setup: develop
image:
  repository: {}
  pullSecret: {}
nameOverride: template-mapper
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
autoscaling: {}
resourcesJobs: {}
resources:
  requests:
    memory: "256Mi"
    cpu: "50m"
  limits:
    memory: "768Mi"
    cpu: "500m"
livenessProbe: {}
readinessProbe: {}
startupProbe: {}
lifecycle: {}
template-mapper:
  labels:
    app: template-mapper
ingress:
  annotations: {}
  gzip:
    enabled: true
    compLevel: 5
    minLength: 1024
annotations:
  ci.elma365.com/commit: "d074b4bd"
  ci.elma365.com/checksum: "33ee6563"
  ci.elma365.com/job_id: "3402262"
  ci.elma365.com/timestamp: "2025-07-07T10:50:28+04:00"
  ci.elma365.com/pipeline_id: "599576"
